# Generated by Django 6.1.1 on 2026-09-19 05:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('tartib', models.PositiveSmallIntegerField(default=0)),
                ('faolmi', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tartib', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('ism', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('bloklangan', models.BooleanField(default=False)),
                ('yaratildi', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-yaratildi'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faolmi', models.BooleanField(default=True)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savatlar', to='restaurant_app.customer')),
            ],
            options={
                'ordering': ['-yangilangan'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('tavsif', models.TextField(blank=True)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='taomlar/')),
                ('tayyorlanish_vaqti', models.PositiveSmallIntegerField(default=15)),
                ('faolmi', models.BooleanField(default=True)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taomlar', to='restaurant_app.category')),
            ],
            options={
                'ordering': ['kategoriya__tartib', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('qoshilgan', models.DateTimeField(auto_now_add=True)),
                ('savat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qatorlar', to='restaurant_app.cart')),
                ('taom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.dish')),
            ],
            options={
                'ordering': ['qoshilgan'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.CharField(db_index=True, max_length=16, unique=True)),
                ('holat', models.CharField(choices=[('yangi', 'Yangi'), ('tayyorlanmoqda', 'Tayyorlanmoqda'), ('tayyor', 'Tayyor'), ('berildi', 'Berildi'), ('yetkazildi', 'Yetkazildi'), ('bekor_qilindi', 'Bekor qilindi')], db_index=True, default='yangi', max_length=20)),
                ('yetkazish_turi', models.CharField(choices=[('stol', 'Stolda'), ('manzil', 'Yetkazib berish')], max_length=10)),
                ('stol_raqami', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('manzil', models.CharField(blank=True, max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('izoh', models.TextField(blank=True)),
                ('jami_summa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('yetkazish_narxi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tayyor_vaqti', models.DateTimeField(blank=True, null=True)),
                ('yopilgan_vaqti', models.DateTimeField(blank=True, null=True)),
                ('bekor_sababi', models.CharField(blank=True, max_length=255)),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyurtmalar', to='restaurant_app.customer')),
            ],
            options={
                'ordering': ['-yaratilgan'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taom_nomi', models.CharField(max_length=120)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miqdor', models.PositiveSmallIntegerField()),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qatorlar', to='restaurant_app.order')),
                ('taom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyurtma_qatorlari', to='restaurant_app.dish')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eski_holat', models.CharField(max_length=20)),
                ('yangi_holat', models.CharField(max_length=20)),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarix', to='restaurant_app.order')),
                ('kim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vaqt'],
            },
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('faolmi', True)), fields=('mijoz',), name='bitta_faol_savat'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.UniqueConstraint(fields=('kategoriya', 'nom'), name='unique_dish_per_category'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(condition=models.Q(('narx__gt', 0)), name='dish_narx_positive'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('savat', 'taom'), name='unique_cart_item_per_dish'),
        ),
    ]
